### ISSUE TITLE
Connection.runOperation() and runQuery() may not close the cursor, either

### ISSUE THREAD

**Issue by mrwonko** [wulczer/txpostgres#37]
Prompted by #35 I took a look at runQuery() and runOperation(), and they seem to have the same problem as runInteraction() in case of failure. I tried fixing it the same way you fixed runInteraction() but that broke the disconnectWhileRunning test - cursor.close() mustn't be called while the query is still running, but connectionLost() calls the errback (I think?).

**Comment by wulczer** [comment]
Hm, this made me rethink the whole cursor-closing chase and I came up with 7ecefe5ab8bba8b8de2282c117e53522050a745c

Using the same strategy `runInteraction()` used caused the test to fail, because if the parent psycopg2 connection is closed, you can't close the cursor without getting an error. This resulted in a spurious `log.err()` which led to the test failing.

See the commit message for 7ecefe5ab8bba8b8de2282c117e53522050a745c for the rationale...

Does this sound reasonable?

**Comment by mrwonko** [comment]
If cursors indeed do not need to be closed then it's fine not to close them, sure.

It just feels somewhat unintuitive that this would be the case. Are they automatically cleaned up or will I end up with thousands of open cursors over the lifetime of my application?

**Comment by wulczer** [comment]
Per http://initd.org/psycopg/docs/cursor.html#cursor.close

```
close()

Close the cursor now (rather than whenever del is executed)
```

When the created cursors will get garbage collected, they'll get closed by psycopg2.

Note that what DBAPI-2.0 calls a "cursor" is not what the SQL standard calls a "cursor". In psycopg2 it's just a lightweight object, without much real utility. It has nothing to do with named cursors as described in http://www.postgresql.org/docs/current/static/plpgsql-cursors.html

Like I said, the only utility in closing a psycopg2's cursor is to ensure it won't be used again. For cursors that the user never touches, it doesn't matter.

**Comment by mrwonko** [comment]
Alright.

But is it possible for a Cursor to be deleted before a Query is finished? Wouldn't that lead to the same error?

**Comment by wulczer** [comment]
A cursor won't be garbage collected before the query is done, so there's no issue there.

The test fails, beause it expliclty closes the connection while there's a query underway. If someone does that, getting exceptions is expected.
