### ISSUE TITLE
zope implements vs implementer for Python3

### ISSUE THREAD

**Issue by FirefighterBlu3** [wulczer/txpostgres#38]
In short, `implements(foo)` is for python2 while in python3, you use the decorator `@implementer(foo)`.

See https://github.com/Pylons/pyramid/issues/604 for discussion.

This problem is encountered at start of `class _PolingMixin`

**Comment by wulczer** [comment]
Thanks for the heads up, however since txpostgres is a driver for Twisted and Twisted itself does not run on Python 3 yet, I haven't done any testing with it yet.

Once Twisted releases a Python 3 compatible version, I'll make sure to make txpostgres compatible!
